# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 153b5da559841cbe545f2788e04c027ed5a4083899b06c5cc48b30b8f9129b4f549e9f4297d3a24dc32e0bc7ddc5fe9947fa2667efc65b8e65635b253b889c52
  iltwyid: <%= ENV["ILTWY_APP_ID"] %>
  iltwysecret: <%= ENV["ILTWY_APP_SECRET"] %>
test:
  secret_key_base: afdcbff1426469e8c0d92225faf86b60ccc6280fc6e3daea9869c85355f78c48ae9179b14b8d26845551be57246ec838c488e3e1b3f2e2b9ccc7155ea3d646cd
  iltwyid: <%= ENV["ILTWY_APP_ID"] %>
  iltwysecret: <%= ENV["ILTWY_APP_SECRET"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  iltwyid: <%= ENV["ILTWY1_APP_ID"] %>
  iltwysecret: <%= ENV["ILTWY1_APP_SECRET"] %>
